project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('store.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

store/urls.py
from django.urls import path
from store import views

app_name = 'store'

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search'), 

    # Product CRUD 
    path('product/<int:product_id>/', views.product, name='product'), # Read
    path('product/create/', views.create, name='create'), # Create
    path('product/<int:product_id>/update/', views.update, name='update'), # Update
    path('product/<int:product_id>/delete/', views.delete, name='delete'), # Delete

    # user
    path('user/create/', views.register, name='register'),
    path('user/login/', views.login_view, name='login'),
    path('user/logout/', views.logout_view, name='logout'),
]

store/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Depois:
# Retirar os campos "blank" e "null" dos Product.owner pois sempre terão donos.
# Criar carrinho para usuario.

class Category(models.Model):
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'
    
    name = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.name}'

class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    amount = models.PositiveIntegerField()
    created_date = models.DateTimeField(default=timezone.now)
    picture = models.ImageField(blank=True, upload_to='pictures/%Y/%m/')
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        blank=False, null=True
    )
    owner = models.ForeignKey(
        User,
        on_delete=models.CASCADE, # Se o usuário for excluido, todos os produtos relacionados também serão.
        blank=True, null=True
    )

    def __str__(self):
        
        return f'{self.name} - {self.owner} - {self.category}'

store/forms.py
# ORGANIZAR ESTE FORMS, DELETAR TESTES DE CODIGOS COMO TESTES DE ERROS E COMENTARIOS.
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from django import forms
from django.contrib.auth.models import User
from . import models

class ProductForm(forms.ModelForm):

    picture = forms.ImageField(
        widget=forms.FileInput(
            attrs={
                'accept': 'image/*',
            }
        )
    )

    name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'classe-a classe-b',
                'placeholder': 'Aqui veio do init',
            }
        ),
        label='Primeiro Nome',
        help_text='Texto de ajuda para seu usuário',
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # self.fields['name'].widget.attrs.update({
        #     'class': 'classe-a classe-b',
        #     'placeholder': 'Aqui veio do init',
        # })

    class Meta:
        model = models.Product
        fields = (
            'name', 'price', 'description', 'category', 'amount', 'picture',
        )

        # widgets = {
        #     'first_name': forms.TextInput(
        #         attrs={
        #             'class': 'classe-a classe-b',
        #             'placeholder': 'Escreva aqui',
        #         }
        #     )
        # }

    # Se a validação depende de mais de um campo, use clean(self).
    def clean(self):
        cleaned_data = self.cleaned_data
        price = cleaned_data.get('price')
        amount = cleaned_data.get('amount')

        if price == amount:
            msg = ValidationError(
                'Preço não pode ser igual a quantidade',
                code='invalid'
            )

            self.add_error('price', msg)
            self.add_error('amount', msg)
        
        return super().clean()
    
    # Se a validação for específica de um único campo, crie clean_nomeDoCampo().
    def clean_name(self):
       name = self.cleaned_data.get('name')

       if name == 'ABC':
           self.add_error(
               'name',
               ValidationError(
                    'Veio do add_error',
                    code='invalid'
                )
            )
        
       return name

class RegisterForm(UserCreationForm):
    first_name = forms.CharField(
        required=True,
        min_length=3,
    )
    last_name = forms.CharField(
        required=True,
        min_length=3,
    )
    email = forms.EmailField()

    class Meta:
        model = User
        fields = (
            'first_name', 'last_name', 'email',
            'username', 'password1', 'password2',
        )

    def clean_email(self):
        email = self.cleaned_data.get('email')

        if User.objects.filter(email=email).exists():
            self.add_error(
                'email',
                ValidationError('Já existe este e-mail', code='invalid')
            )

        return email

store/views.py
from django.shortcuts import render

def index(request):
    return render(
        request,
        'store/index.html'
    )

store/views/product_forms.py
from store.forms import ProductForm
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse
from store.models import Product

def create(request):
    form_action = reverse('store:create')

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)

        context = {
            'form': form,
            'form_action': form_action, 
        }

        if form.is_valid():
            product = form.save()
            return redirect('store:update', product_id=product.pk)

        return render(
            request,
            'store/create.html',
            context
        )

    context = {
        'form': ProductForm(),
        'form_action': form_action,
    }

    return render(
        request,
        'store/create.html',
        context
    )

def update(request, product_id):
    product = get_object_or_404(
        Product, pk=product_id, 
    )
    form_action = reverse('store:update', args=(product_id,))

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)

        context = {
            'form': form,
            'form_action': form_action, 
        }

        if form.is_valid():
            product = form.save()
            return redirect('store:update', product_id=product.pk)

        return render(
            request,
            'store/create.html',
            context
        )

    context = {
        'form': ProductForm(instance=product),
        'form_action': form_action,
    }

    return render(
        request,
        'store/create.html',
        context
    )

def delete(request, product_id):
    product = get_object_or_404(
        Product, pk=product_id
    )

    confirmation = request.POST.get('confirmation', 'no')

    if confirmation == 'yes':
        product.delete()
        return redirect('store:index')
    
    return render(
        request,
        'store/product.html',
        {
            'product': product,
            'confirmation': confirmation,
        }
    )

store/views/store_views.py
from store.models import Product
from django.db.models import Q
# from django.contrib import messages
from django.shortcuts import get_object_or_404, render, redirect

def index(request):
    products = Product.objects.order_by('-id')
    
    context = {
        'products': products,
        'site_title': 'Products - ',
    }

    return render(
        request,
        'store/index.html',
        context
    )

def search(request):             # Se o parâmetro "q" estiver vazio, retorne ''.
    search_value = request.GET.get('q', '').strip()

    if search_value == '':
        return redirect('store:index')

    products = Product.objects \
        .filter(
            Q(name__icontains=search_value) |
            Q(category__name__icontains=search_value) |  # Busca pelo nome da categoria
            Q(owner__username__icontains=search_value)   # Busca pelo nome do usuário
        )\
        .order_by('-id')
    
    # # Redireciona se nenhum produto for encontrado (fiz de outra forma direto nos templates)
    # if not products.exists():
    #     messages.warning(request, f'O produto/categoria/fornecedor "{search_value}" não foi encontrado.')
    #     return redirect('store:index')
    
    context = {
        'products': products,
        'site_title': 'Search - ',
        'search_value': search_value,
    }

    return render(
        request,
        'store/index.html',
        context
    )

def product(request, product_id):
    # single_product = Product.objects.filter(pk=product_id).first()
    single_product = get_object_or_404(
        Product, pk=product_id
    )
    context = {
        'product': single_product,
        'site_title': f'{single_product.name} - '
    }
    return render(
        request,
        'store/product.html',
        context
    )

store/views/user_forms.py
from django.shortcuts import render, redirect
from django.contrib import auth, messages
from store.forms import RegisterForm
from django.contrib.auth.forms import AuthenticationForm


def register(request):
    form = RegisterForm()

    if request.method == 'POST':
        form = RegisterForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request, 'Usuário salvo')
            return redirect('store:login')

    return render(
        request,
        'store/register.html',
        {
            'form': form
        }
    )

def login_view(request):
    form = AuthenticationForm(request)

    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)

        if form.is_valid():
            user = form.get_user()
            auth.login(request, user)
            messages.success(request, 'Logado com sucesso!')
            return redirect('store:index')
        
        messages.error(request, 'Login inválido')

    return render(
        request,
        'store/login.html',
        {
            'form': form
        }
    )


def logout_view(request):
    auth.logout(request)
    return redirect('store:login')

store/templates/store/create.html
{% extends "global/base.html" %}
{% block content %}

<div class="form-wrapper">
    <h2>Product</h2>
    
    <form action="{{ form_action }}" method="POST" enctype="multipart/form-data">

        {% csrf_token %}

        <div class="form-content">

            {% for field in form %}
                <div class="form-group">
                    <label for={{ field.id_for_label}}>{{ field.label }}</label>
                    {{ field }}
                    {{ field.errors}}

                    {% if field.help_text %}
                        <p class="help-text">{{ field.help_text }}</p>
                    {% endif %}
                </div> 

            {% if field.name == 'picture' and field.value.url %}
                <div class="form-group">
                    <img src="{{ field.value.url }}" alt="{{ product.name }}" width="120em">
                </div>
            {% endif %}

            {% endfor %}

        </div>

        {% if form.non_field_errors %}

            <div class="form-content">
                
                <div class="form-group">
                    
                    <div class="message error">
                        {{ form.non_field_errors }}
                    </div>
                
                </div>
            
            </div>
      
        {% endif %}

        <div class="form-content">
            <div class="form-group">
                <button class="btn" type="submit">Send</button>
            </div>
        </div>

    </form>
</div>

{% endblock content %}

store/templates/store/index.html
{% extends "global/base.html" %}

{% block content %}
  {% if products %}
    
  <div class="product-grid">
      {% for product in products %}
        <div class="product-card">
          {% if product.picture %}
            <img src="{{ product.picture.url }}" alt="{{ product.name }}" width="120em">
          {% else %}
            <h2>{{ product.name }}</h2>
          {% endif %}
          <p class="price">R${{ product.price }}</p>
          <p class="category">{{ product.category }}</p>
          <a href="{% url 'store:product' product.id %}">Ver Detalhes</a>
        </div>
      {% endfor %}
    </div>
    
  {% else %}
    
    <div class="product-details">
      <h1>O produto/categoria/fornecedor "{{search_value}}" não foi encontrado.</h1>
    </div>
  
  {% endif %}
{% endblock content %}

store/templates/store/login.html
{% extends 'global/base.html' %}

{% block content %}
    
    <div class="form-wrapper">

        <h2>Login </h2>

        {% if user.is_authenticated %}
            <p>
                Você fez login como {{ user.username }}.
                Clique <a href="{% url 'store:logout' %}">aqui</a>
                para sair.
            </p>

        {% else %}
            {% include 'store/partials/_user-form.html' %}
        {% endif %}
    
    </div>
{% endblock content %}

store/templates/store/product.html
{% extends 'global/base.html' %}
{% block content %}
  <div class="product-details">
    <h1>{{ product.name }}</h1>
    <p><b>ID:</b> {{ product.id }}</p>
    <p><b>Price:</b> R${{ product.price }}</p>
    <p><b>Category:</b> {{ product.category }}</p>
    <p><b>Owner:</b> {{ product.owner }}</p>
    <p><b>Created Date:</b> {{ product.created_date }}</p>
    <p><b>Description:</b> {{ product.description }}</p>

    {% if product.picture %}
      <p>
        <img src="{{ product.picture.url }}" alt="{{ product.name }}" width="120em">
      </p>
    {% endif %}

  </div>

  <div class="product-links">
    <a href="{% url 'store:update' product.id %}" class="btn btn-link">Update</a>

    <form action="{% url 'store:delete' product.id %}" method="POST">
      {% csrf_token %}

      {% if confirmation == 'no' %}

        <input type="hidden" name="confirmation" value="yes">
        <button class="btn btn-link btn-delete" type="submit">Confirma?</button>
      
      {% else %}
        
        <button class="btn btn-link btn-delete" type="submit">Delete</button>
      
      {% endif %}

    </form>

  </div>
{% endblock content %}

store/templates/store/register.html
{% extends 'global/base.html' %}

{% block content %}
    <div class="form-wrapper">

        <h2>Register</h2>

        {% include 'store/partials/_user-form.html' %}

    </div>
{% endblock content %}